
package com.gyj.utils.sm4;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Sm4WSImpl", targetNamespace = "http://ws.dhcc_sm4.dhcc.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Sm4WSImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encryptInfo", targetNamespace = "http://ws.dhcc_sm4.dhcc.com.cn/", className = "com.gyj.utils.sm4.EncryptInfo")
    @ResponseWrapper(localName = "encryptInfoResponse", targetNamespace = "http://ws.dhcc_sm4.dhcc.com.cn/", className = "com.gyj.utils.sm4.EncryptInfoResponse")
    @Action(input = "http://ws.dhcc_sm4.dhcc.com.cn/Sm4WSImpl/encryptInfoRequest", output = "http://ws.dhcc_sm4.dhcc.com.cn/Sm4WSImpl/encryptInfoResponse")
    public String encryptInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "decryptInfo", targetNamespace = "http://ws.dhcc_sm4.dhcc.com.cn/", className = "com.gyj.utils.sm4.DecryptInfo")
    @ResponseWrapper(localName = "decryptInfoResponse", targetNamespace = "http://ws.dhcc_sm4.dhcc.com.cn/", className = "com.gyj.utils.sm4.DecryptInfoResponse")
    @Action(input = "http://ws.dhcc_sm4.dhcc.com.cn/Sm4WSImpl/decryptInfoRequest", output = "http://ws.dhcc_sm4.dhcc.com.cn/Sm4WSImpl/decryptInfoResponse")
    public String decryptInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
